// Generated by `bun init`

// File System Access API — not yet in the TypeScript DOM lib
interface SaveFilePickerOptions {
  suggestedName?: string;
  types?: Array<{
    description?: string;
    accept: Record<string, string[]>;
  }>;
  excludeAcceptAllOption?: boolean;
}

interface OpenFilePickerOptions {
  multiple?: boolean;
  types?: Array<{
    description?: string;
    accept: Record<string, string[]>;
  }>;
  excludeAcceptAllOption?: boolean;
}

interface Window {
  showSaveFilePicker(options?: SaveFilePickerOptions): Promise<FileSystemFileHandle>;
  showOpenFilePicker(options?: OpenFilePickerOptions): Promise<FileSystemFileHandle[]>;
}

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "*.css" { }

/**
 * Public environment variables embedded at build time via `bun build --env='BUN_PUBLIC_*'`.
 * Set these in a `.env` file at the project root:
 *
 *   BUN_PUBLIC_MAPBOX_TOKEN=pk.eyJ1...
 */
declare namespace NodeJS {
  interface ProcessEnv {
    /** Mapbox public access token for satellite tile rendering. */
    BUN_PUBLIC_MAPBOX_TOKEN?: string;
  }
}
